import socket
sock = socket.socket()
port = input("Server Port: ")
host_server = input("Server Host Name: ")
sock.connect((host_server, int(port)))
sock.send("403 ERROR\nThe request could not be satisfied.\nThe Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\nGenerated by cloudfront (CloudFront)\nRequest ID: 02jOucoFpGni2NF_QfzqAPapqkcibJn_2NI8Bk3rmFfi2PVER-Cd5A==".encode())
msg = sock.recv(1024)
print(msg.decode())




