name: Build Client and Server

on: [push]

jobs:
  build:
    name: Build    
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    environment: production

    permissions:
      contents: "read"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - run: python3 -m pip install -r requirements.txt
      
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: ircreinvent_noway/client/client.py
          standalone: true

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: ircreinvent_noway/server/server.py
          standalone: true
          
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
